version: '3.8'

services:
  # Backend API
  backend:
    build: ./backend
    container_name: rules-backend
    env_file:
      - .env
    ports:
      - "3001:3001"
    volumes:
      - ./backend/src:/app/src
    command: npm run dev

  # Frontend React app
  frontend:
    build: ./frontend
    container_name: rules-frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    command: npm run dev
